### ISSUE TITLE
Don´t follow 

### ISSUE THREAD

**Issue by mcolus** [ncs15/InstagramBot#2]
When the Bot have to follow people, eject this error:

```
2020-10-23 13:46:01.289845 Interaction with : Instagram:_user
NO of likes: 128
Traceback (most recent call last):
  File "/Users/Downloads/InstagramBot-main/AgentLogic.py", line 238, in check_hashtag
    followed_users = Users.get_today_followed()
  File "/Users/Downloads/InstagramBot-main/Users.py", line 80, in get_today_followed
    cursor.execute(f"SELECT * FROM followed_users WHERE date_added='{now}'")
sqlite3.OperationalError: no such table: followed_users
```

**Comment by ncs15** [comment]
Hey. Now it should work.
Can you make a test with the changes?
It was because the db was empty. Never tried this combination 👍  
I will close the issue if is ok.

**Comment by mcolus** [comment]
Again an Issue

```
cursor.execute("SELECT * FROM viewed_users")
sqlite3.OperationalError: no such table: viewed_users
```

**Comment by mcolus** [comment]
Error found, I have not entered the way to the directory.
Maybe it would be good to include in the documentation that the path from the "chromewebdriver" has to be entered in the "settings.json".
The path of the "settings.json" in the "ConfigHandler.py".
Also the path from "dbo.db" in "user.py".
At least it is like this on my Mac. 
I'm just testing and if it should run without problems I will mark the problem as solved.
